apiVersion: apps/v1
kind: Deployment
metadata:
  name: colorapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: colorapp
  template:
    metadata:
      labels:
        app: colorapp
    spec:
      containers:
        - name: colorapp
          image: srujanatangudu4/sample:colorapp1
          ports:
            - containerPort: 5000
