apiVersion: v1
kind: Service
metadata:
  name: colorapp-service
spec:
  selector:
    app: colorapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30344
  type: NodePort
